### ISSUE TITLE
uinput not found

### ISSUE THREAD

**Issue by jensgrunzer1** [sbidolach/mobile-gamepad#20]
Whenever i try to execute it(sudo grunt start), it complains about not finding uinput. I installed uninput manually(npm i uinput) but it still doesnt work.
logs:
` Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "copy:public" (copy) task
Created 1 directory, copied 3 files

Running "copy:client" (copy) task
Created 3 directories, copied 10 files

Running "express:dev" (express) task
Starting background Express server
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'uinput'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/mobile-gamepad/server/src/gamepad.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Stopping Express server

Running "watch" task
Waiting... `

**Comment by AzizBgBoss** [comment]
In the mobile-gamepad directory, do `npm install uinput`

If it worked, congrats.
If not, do `ls node_modules | grep uinput`
if you find a directory named "uinput2", do `mv node_modules/uinput2 node_modules/uinput`
then try again...

**Comment by rohith1005H** [comment]
Root cause found and fixed in #21.

`npm install` fetches `timstableford/node-uinput`, but that package renamed itself to `uinput2` in July 2021. npm 5.8 (what Raspbian Buster / RetroPie ships) names the folder after the package's own name and then drops it because no dependency key requests `uinput2`, so the install "succeeds" but `node_modules/uinput` never exists. Installing `npm i uinput` by hand pulls the unrelated old registry package, which is why that did not help either.

Workaround until the PR is merged, run inside `~/mobile-gamepad`:

```bash
sed -i 's/"uinput": "git+/"uinput2": "git+/' package.json
sed -i "s/require('uinput')/require('uinput2')/" server/src/gamepad.js
npm install
sudo grunt start
```

Verified working on a Pi 4 with RetroPie, Node 10.24 / npm 5.8.
